---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
headerStyle: boxed
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
  random: random

layout:
  System Health:
  Services:
  Game Servers:
  Control Panels:
    style: row
