---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
headerStyle: boxed
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
  random: random

layout:
  Row 1:
    header: false
    style: row
    columns: 3
  Control Panels:
    style: row
    columns: 3